-- Seed data for my-website D1 database
-- Generated: 2026-03-15T09:36:58.368Z

-- Clear existing data
DELETE FROM photos;
DELETE FROM destinations;

-- Insert destinations
INSERT INTO destinations (id, name_en, name_cs, description_en, description_cs, lat, lng, continent, visited_at_year) VALUES ('iceland', 'Iceland', 'Iceland', 'Land of fire and ice — volcanic landscapes, glaciers, waterfalls, and endless horizons from the drone.', 'Land of fire and ice — volcanic landscapes, glaciers, waterfalls, and endless horizons from the drone.', 64.75, -17.84, 'Europe', 2019);
INSERT INTO destinations (id, name_en, name_cs, description_en, description_cs, lat, lng, continent, visited_at_year) VALUES ('canadian-rockies', 'Canadian Rockies', 'Canadian Rockies', 'Turquoise lakes, towering peaks, and pristine wilderness across British Columbia and Alberta.', 'Turquoise lakes, towering peaks, and pristine wilderness across British Columbia and Alberta.', 52.24, -118.62, 'North America', 2019);
INSERT INTO destinations (id, name_en, name_cs, description_en, description_cs, lat, lng, continent, visited_at_year) VALUES ('malaysia', 'Malaysia', 'Malaysia', 'Tropical beaches, Kuala Lumpur skyline, and lush jungles of Southeast Asia.', 'Tropical beaches, Kuala Lumpur skyline, and lush jungles of Southeast Asia.', 4.31, 100.99, 'Asia', 2020);
INSERT INTO destinations (id, name_en, name_cs, description_en, description_cs, lat, lng, continent, visited_at_year) VALUES ('bali', 'Bali', 'Bali', 'Rice terraces, temple ceremonies, dramatic cliffs, and endless sunsets over the Indian Ocean.', 'Rice terraces, temple ceremonies, dramatic cliffs, and endless sunsets over the Indian Ocean.', -8.47, 115.27, 'Asia', 2022);
INSERT INTO destinations (id, name_en, name_cs, description_en, description_cs, lat, lng, continent, visited_at_year) VALUES ('yosemite', 'Yosemite', 'Yosemite', 'Granite cliffs, giant sequoias, and the breathtaking valley views of California''s crown jewel.', 'Granite cliffs, giant sequoias, and the breathtaking valley views of California''s crown jewel.', 37.77, -119.81, 'North America', 2022);
INSERT INTO destinations (id, name_en, name_cs, description_en, description_cs, lat, lng, continent, visited_at_year) VALUES ('silicon-valley', 'Silicon Valley', 'Silicon Valley', 'The tech capital of the world — aerial views over San Jose and the Bay Area.', 'The tech capital of the world — aerial views over San Jose and the Bay Area.', 37.34, -122.01, 'North America', 2022);
INSERT INTO destinations (id, name_en, name_cs, description_en, description_cs, lat, lng, continent, visited_at_year) VALUES ('mexican-caribbean', 'Mexican Caribbean', 'Mexican Caribbean', 'Turquoise waters, ancient Mayan ruins, cenotes, and white sand beaches along the Riviera Maya.', 'Turquoise waters, ancient Mayan ruins, cenotes, and white sand beaches along the Riviera Maya.', 20.8, -87.19, 'North America', 2023);
INSERT INTO destinations (id, name_en, name_cs, description_en, description_cs, lat, lng, continent, visited_at_year) VALUES ('yucatan', 'Yucatán', 'Yucatán', 'Pink flamingo lagoons, Mayan pyramids, and colorful colonial towns deep in the Mexican interior.', 'Pink flamingo lagoons, Mayan pyramids, and colorful colonial towns deep in the Mexican interior.', 20.58, -89.35, 'North America', 2023);
INSERT INTO destinations (id, name_en, name_cs, description_en, description_cs, lat, lng, continent, visited_at_year) VALUES ('guatemala', 'Guatemala', 'Guatemala', 'Volcanoes, misty highlands, Lake Atitlán, and the ancient ruins of Tikal from above.', 'Volcanoes, misty highlands, Lake Atitlán, and the ancient ruins of Tikal from above.', 14.99, -90.21, 'North America', 2023);
INSERT INTO destinations (id, name_en, name_cs, description_en, description_cs, lat, lng, continent, visited_at_year) VALUES ('ecuador', 'Ecuador', 'Ecuador', 'The equator line, Andean highlands, cloud forests, and the diversity of a tiny, mighty country.', 'The equator line, Andean highlands, cloud forests, and the diversity of a tiny, mighty country.', -0.25, -78.38, 'South America', 2024);
INSERT INTO destinations (id, name_en, name_cs, description_en, description_cs, lat, lng, continent, visited_at_year) VALUES ('colombia', 'Colombia', 'Colombia', 'Caribbean coastline, colonial Cartagena, lush coffee country, and vibrant cities from the sky.', 'Caribbean coastline, colonial Cartagena, lush coffee country, and vibrant cities from the sky.', 8.73, -74.55, 'South America', 2024);
INSERT INTO destinations (id, name_en, name_cs, description_en, description_cs, lat, lng, continent, visited_at_year) VALUES ('costa-rica', 'Costa Rica', 'Costa Rica', 'Pura vida — rainforests, volcanoes, wild coastlines, and incredible biodiversity.', 'Pura vida — rainforests, volcanoes, wild coastlines, and incredible biodiversity.', 9.3, -84.16, 'North America', 2024);
INSERT INTO destinations (id, name_en, name_cs, description_en, description_cs, lat, lng, continent, visited_at_year) VALUES ('panama', 'Panama', 'Panama', 'Where two oceans meet — tropical islands, misty highlands, and the famous canal from above.', 'Where two oceans meet — tropical islands, misty highlands, and the famous canal from above.', 9.63, -82.67, 'North America', 2024);

-- Insert photos
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('iceland-DJI_0006', 'iceland', 'DJI_0006.webp', 'DJI_0006-thumb.webp', 'DJI_0006-blur.webp', NULL, NULL, 0, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('iceland-DJI_0027', 'iceland', 'DJI_0027.webp', 'DJI_0027-thumb.webp', 'DJI_0027-blur.webp', NULL, NULL, 1, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('iceland-DJI_0036', 'iceland', 'DJI_0036.webp', 'DJI_0036-thumb.webp', 'DJI_0036-blur.webp', NULL, NULL, 2, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('canadian-rockies-DJI_0018', 'canadian-rockies', 'DJI_0018.webp', 'DJI_0018-thumb.webp', 'DJI_0018-blur.webp', NULL, NULL, 0, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('canadian-rockies-DJI_0022', 'canadian-rockies', 'DJI_0022.webp', 'DJI_0022-thumb.webp', 'DJI_0022-blur.webp', NULL, NULL, 1, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('canadian-rockies-DJI_0070', 'canadian-rockies', 'DJI_0070.webp', 'DJI_0070-thumb.webp', 'DJI_0070-blur.webp', NULL, NULL, 2, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('canadian-rockies-DJI_0090', 'canadian-rockies', 'DJI_0090.webp', 'DJI_0090-thumb.webp', 'DJI_0090-blur.webp', NULL, NULL, 3, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('canadian-rockies-DJI_0092', 'canadian-rockies', 'DJI_0092.webp', 'DJI_0092-thumb.webp', 'DJI_0092-blur.webp', NULL, NULL, 4, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('canadian-rockies-DJI_0111', 'canadian-rockies', 'DJI_0111.webp', 'DJI_0111-thumb.webp', 'DJI_0111-blur.webp', NULL, NULL, 5, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('canadian-rockies-DJI_0125', 'canadian-rockies', 'DJI_0125.webp', 'DJI_0125-thumb.webp', 'DJI_0125-blur.webp', NULL, NULL, 6, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('canadian-rockies-DJI_0140', 'canadian-rockies', 'DJI_0140.webp', 'DJI_0140-thumb.webp', 'DJI_0140-blur.webp', NULL, NULL, 7, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('malaysia-DJI_0022 2', 'malaysia', 'DJI_0022 2.webp', 'DJI_0022 2-thumb.webp', 'DJI_0022 2-blur.webp', NULL, NULL, 0, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('malaysia-DJI_0029', 'malaysia', 'DJI_0029.webp', 'DJI_0029-thumb.webp', 'DJI_0029-blur.webp', NULL, NULL, 1, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('bali-DJI_0049', 'bali', 'DJI_0049.webp', 'DJI_0049-thumb.webp', 'DJI_0049-blur.webp', NULL, NULL, 0, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('bali-DJI_0055', 'bali', 'DJI_0055.webp', 'DJI_0055-thumb.webp', 'DJI_0055-blur.webp', NULL, NULL, 1, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('bali-DJI_0118', 'bali', 'DJI_0118.webp', 'DJI_0118-thumb.webp', 'DJI_0118-blur.webp', NULL, NULL, 2, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('bali-DJI_0149', 'bali', 'DJI_0149.webp', 'DJI_0149-thumb.webp', 'DJI_0149-blur.webp', NULL, NULL, 3, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('bali-DJI_0171', 'bali', 'DJI_0171.webp', 'DJI_0171-thumb.webp', 'DJI_0171-blur.webp', NULL, NULL, 4, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('yosemite-DJI_0154', 'yosemite', 'DJI_0154.webp', 'DJI_0154-thumb.webp', 'DJI_0154-blur.webp', NULL, NULL, 0, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('yosemite-DJI_0160', 'yosemite', 'DJI_0160.webp', 'DJI_0160-thumb.webp', 'DJI_0160-blur.webp', NULL, NULL, 1, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('silicon-valley-DJI_0169', 'silicon-valley', 'DJI_0169.webp', 'DJI_0169-thumb.webp', 'DJI_0169-blur.webp', NULL, NULL, 0, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('silicon-valley-DJI_0179', 'silicon-valley', 'DJI_0179.webp', 'DJI_0179-thumb.webp', 'DJI_0179-blur.webp', NULL, NULL, 1, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('silicon-valley-DJI_0182', 'silicon-valley', 'DJI_0182.webp', 'DJI_0182-thumb.webp', 'DJI_0182-blur.webp', NULL, NULL, 2, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('mexican-caribbean-DJI_0194', 'mexican-caribbean', 'DJI_0194.webp', 'DJI_0194-thumb.webp', 'DJI_0194-blur.webp', NULL, NULL, 0, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('mexican-caribbean-DJI_0203', 'mexican-caribbean', 'DJI_0203.webp', 'DJI_0203-thumb.webp', 'DJI_0203-blur.webp', NULL, NULL, 1, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('mexican-caribbean-DJI_0216', 'mexican-caribbean', 'DJI_0216.webp', 'DJI_0216-thumb.webp', 'DJI_0216-blur.webp', NULL, NULL, 2, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('mexican-caribbean-DJI_0258', 'mexican-caribbean', 'DJI_0258.webp', 'DJI_0258-thumb.webp', 'DJI_0258-blur.webp', NULL, NULL, 3, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('mexican-caribbean-DJI_0265', 'mexican-caribbean', 'DJI_0265.webp', 'DJI_0265-thumb.webp', 'DJI_0265-blur.webp', NULL, NULL, 4, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('mexican-caribbean-DJI_0271', 'mexican-caribbean', 'DJI_0271.webp', 'DJI_0271-thumb.webp', 'DJI_0271-blur.webp', NULL, NULL, 5, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('mexican-caribbean-DJI_0274', 'mexican-caribbean', 'DJI_0274.webp', 'DJI_0274-thumb.webp', 'DJI_0274-blur.webp', NULL, NULL, 6, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('mexican-caribbean-DJI_0275', 'mexican-caribbean', 'DJI_0275.webp', 'DJI_0275-thumb.webp', 'DJI_0275-blur.webp', NULL, NULL, 7, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('mexican-caribbean-DJI_0346', 'mexican-caribbean', 'DJI_0346.webp', 'DJI_0346-thumb.webp', 'DJI_0346-blur.webp', NULL, NULL, 8, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('mexican-caribbean-DJI_0361', 'mexican-caribbean', 'DJI_0361.webp', 'DJI_0361-thumb.webp', 'DJI_0361-blur.webp', NULL, NULL, 9, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('yucatan-DJI_0327', 'yucatan', 'DJI_0327.webp', 'DJI_0327-thumb.webp', 'DJI_0327-blur.webp', NULL, NULL, 0, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('yucatan-DJI_0336', 'yucatan', 'DJI_0336.webp', 'DJI_0336-thumb.webp', 'DJI_0336-blur.webp', NULL, NULL, 1, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('yucatan-DJI_0495', 'yucatan', 'DJI_0495.webp', 'DJI_0495-thumb.webp', 'DJI_0495-blur.webp', NULL, NULL, 2, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('yucatan-DJI_0500', 'yucatan', 'DJI_0500.webp', 'DJI_0500-thumb.webp', 'DJI_0500-blur.webp', NULL, NULL, 3, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('yucatan-DJI_0503', 'yucatan', 'DJI_0503.webp', 'DJI_0503-thumb.webp', 'DJI_0503-blur.webp', NULL, NULL, 4, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('yucatan-DJI_0521', 'yucatan', 'DJI_0521.webp', 'DJI_0521-thumb.webp', 'DJI_0521-blur.webp', NULL, NULL, 5, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('guatemala-DJI_0539', 'guatemala', 'DJI_0539.webp', 'DJI_0539-thumb.webp', 'DJI_0539-blur.webp', NULL, NULL, 0, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('guatemala-DJI_0559', 'guatemala', 'DJI_0559.webp', 'DJI_0559-thumb.webp', 'DJI_0559-blur.webp', NULL, NULL, 1, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('guatemala-DJI_0573', 'guatemala', 'DJI_0573.webp', 'DJI_0573-thumb.webp', NULL, NULL, NULL, 2, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('ecuador-DJI_0596', 'ecuador', 'DJI_0596.webp', 'DJI_0596-thumb.webp', NULL, NULL, NULL, 0, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('ecuador-DJI_0607', 'ecuador', 'DJI_0607.webp', 'DJI_0607-thumb.webp', NULL, NULL, NULL, 1, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('ecuador-DJI_0610', 'ecuador', 'DJI_0610.webp', 'DJI_0610-thumb.webp', NULL, NULL, NULL, 2, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('ecuador-DJI_0635', 'ecuador', 'DJI_0635.webp', 'DJI_0635-thumb.webp', NULL, NULL, NULL, 3, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('colombia-DJI_0659', 'colombia', 'DJI_0659.webp', 'DJI_0659-thumb.webp', NULL, NULL, NULL, 0, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('colombia-DJI_0701', 'colombia', 'DJI_0701.webp', 'DJI_0701-thumb.webp', NULL, NULL, NULL, 1, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('colombia-DJI_0712', 'colombia', 'DJI_0712.webp', 'DJI_0712-thumb.webp', NULL, NULL, NULL, 2, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('colombia-DJI_0753', 'colombia', 'DJI_0753.webp', 'DJI_0753-thumb.webp', NULL, NULL, NULL, 3, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('colombia-DJI_0766', 'colombia', 'DJI_0766.webp', 'DJI_0766-thumb.webp', NULL, NULL, NULL, 4, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('colombia-DJI_0802', 'colombia', 'DJI_0802.webp', 'DJI_0802-thumb.webp', NULL, NULL, NULL, 5, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('colombia-DJI_0815', 'colombia', 'DJI_0815.webp', 'DJI_0815-thumb.webp', NULL, NULL, NULL, 6, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('colombia-DJI_0818', 'colombia', 'DJI_0818.webp', 'DJI_0818-thumb.webp', NULL, NULL, NULL, 7, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('colombia-DJI_0859', 'colombia', 'DJI_0859.webp', 'DJI_0859-thumb.webp', NULL, NULL, NULL, 8, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('costa-rica-DJI_0805', 'costa-rica', 'DJI_0805.webp', 'DJI_0805-thumb.webp', NULL, NULL, NULL, 0, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('costa-rica-DJI_0817', 'costa-rica', 'DJI_0817.webp', 'DJI_0817-thumb.webp', NULL, NULL, NULL, 1, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('costa-rica-DJI_0849', 'costa-rica', 'DJI_0849.webp', 'DJI_0849-thumb.webp', NULL, NULL, NULL, 2, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('costa-rica-DJI_0881', 'costa-rica', 'DJI_0881.webp', 'DJI_0881-thumb.webp', NULL, NULL, NULL, 3, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('panama-DJI_0768', 'panama', 'DJI_0768.webp', 'DJI_0768-thumb.webp', NULL, NULL, NULL, 0, 1);
INSERT INTO photos (id, destination_id, full_url, thumb_url, blur_url, caption_en, caption_cs, sort_order, is_visible) VALUES ('panama-DJI_0776', 'panama', 'DJI_0776.webp', 'DJI_0776-thumb.webp', NULL, NULL, NULL, 1, 1);

-- Summary: 13 destinations, 61 photos
