export interface TravelPlace {
  id: string;
  name: string;
  description: string;
  lat: number;
  lng: number;
  photos: string[];
  thumbs: string[];
  blurs: (string | undefined)[];
  continent: string;
  continentEmoji: string;
  year: number;
}

const BASE = `${import.meta.env.BASE_URL}travel-map`;

/**
 * Set of photo IDs that have a corresponding *-blur.webp asset committed
 * in public/travel-map. Generated by checking the directory listing.
 */
const HAS_BLUR = new Set([
  'DJI_0006', 'DJI_0018', 'DJI_0022', 'DJI_0022 2', 'DJI_0027', 'DJI_0029',
  'DJI_0036', 'DJI_0049', 'DJI_0055', 'DJI_0070', 'DJI_0090', 'DJI_0092',
  'DJI_0111', 'DJI_0118', 'DJI_0125', 'DJI_0140', 'DJI_0149', 'DJI_0154',
  'DJI_0160', 'DJI_0169', 'DJI_0171', 'DJI_0179', 'DJI_0182', 'DJI_0194',
  'DJI_0203', 'DJI_0216', 'DJI_0258', 'DJI_0265', 'DJI_0271', 'DJI_0274',
  'DJI_0275', 'DJI_0327', 'DJI_0336', 'DJI_0346', 'DJI_0361', 'DJI_0495',
  'DJI_0500', 'DJI_0503', 'DJI_0521', 'DJI_0539', 'DJI_0559',
]);

function makePlace(
  ids: string[],
  meta: Omit<TravelPlace, 'photos' | 'thumbs' | 'blurs'>,
): TravelPlace {
  return {
    ...meta,
    photos: ids.map(f => `${BASE}/${f}.webp`),
    thumbs: ids.map(f => `${BASE}/${f}-thumb.webp`),
    blurs: ids.map(f => HAS_BLUR.has(f) ? `${BASE}/${f}-blur.webp` : undefined),
  };
}

export function getTravelPlaces(t: (key: string) => string): TravelPlace[] {
  return [
    makePlace(['DJI_0006', 'DJI_0027', 'DJI_0036'], {
      id: 'iceland',
      name: t('travel.iceland.name'),
      description: t('travel.iceland.description'),
      lat: 64.75,
      lng: -17.84,
      continent: t('continent.Europe'),
      continentEmoji: '🧊',
      year: 2019,
    }),
    makePlace(['DJI_0018', 'DJI_0022', 'DJI_0070', 'DJI_0090', 'DJI_0092', 'DJI_0111', 'DJI_0125', 'DJI_0140'], {
      id: 'canadian-rockies',
      name: t('travel.canadian-rockies.name'),
      description: t('travel.canadian-rockies.description'),
      lat: 52.24,
      lng: -118.62,
      continent: t('continent.North America'),
      continentEmoji: '🏔️',
      year: 2019,
    }),
    makePlace(['DJI_0022 2', 'DJI_0029'], {
      id: 'malaysia',
      name: t('travel.malaysia.name'),
      description: t('travel.malaysia.description'),
      lat: 4.31,
      lng: 100.99,
      continent: t('continent.Asia'),
      continentEmoji: '🌴',
      year: 2020,
    }),
    makePlace(['DJI_0049', 'DJI_0055', 'DJI_0118', 'DJI_0149', 'DJI_0171'], {
      id: 'bali',
      name: t('travel.bali.name'),
      description: t('travel.bali.description'),
      lat: -8.47,
      lng: 115.27,
      continent: t('continent.Asia'),
      continentEmoji: '🌺',
      year: 2022,
    }),
    makePlace(['DJI_0154', 'DJI_0160'], {
      id: 'yosemite',
      name: t('travel.yosemite.name'),
      description: t('travel.yosemite.description'),
      lat: 37.77,
      lng: -119.81,
      continent: t('continent.North America'),
      continentEmoji: '🏞️',
      year: 2022,
    }),
    makePlace(['DJI_0169', 'DJI_0179', 'DJI_0182'], {
      id: 'silicon-valley',
      name: t('travel.silicon-valley.name'),
      description: t('travel.silicon-valley.description'),
      lat: 37.34,
      lng: -122.01,
      continent: t('continent.North America'),
      continentEmoji: '💻',
      year: 2022,
    }),
    makePlace(['DJI_0194', 'DJI_0203', 'DJI_0216', 'DJI_0258', 'DJI_0265', 'DJI_0271', 'DJI_0274', 'DJI_0275', 'DJI_0346', 'DJI_0361'], {
      id: 'mexican-caribbean',
      name: t('travel.mexican-caribbean.name'),
      description: t('travel.mexican-caribbean.description'),
      lat: 20.80,
      lng: -87.19,
      continent: t('continent.North America'),
      continentEmoji: '🏖️',
      year: 2023,
    }),
    makePlace(['DJI_0327', 'DJI_0336', 'DJI_0495', 'DJI_0500', 'DJI_0503', 'DJI_0521'], {
      id: 'yucatan',
      name: t('travel.yucatan.name'),
      description: t('travel.yucatan.description'),
      lat: 20.58,
      lng: -89.35,
      continent: t('continent.North America'),
      continentEmoji: '🏛️',
      year: 2023,
    }),
    makePlace(['DJI_0539', 'DJI_0559', 'DJI_0573'], {
      id: 'guatemala',
      name: t('travel.guatemala.name'),
      description: t('travel.guatemala.description'),
      lat: 14.99,
      lng: -90.21,
      continent: t('continent.North America'),
      continentEmoji: '🌋',
      year: 2023,
    }),
    makePlace(['DJI_0596', 'DJI_0607', 'DJI_0610', 'DJI_0635'], {
      id: 'ecuador',
      name: t('travel.ecuador.name'),
      description: t('travel.ecuador.description'),
      lat: -0.25,
      lng: -78.38,
      continent: t('continent.South America'),
      continentEmoji: '🌿',
      year: 2024,
    }),
    makePlace(['DJI_0659', 'DJI_0701', 'DJI_0712', 'DJI_0753', 'DJI_0766', 'DJI_0802', 'DJI_0815', 'DJI_0818', 'DJI_0859'], {
      id: 'colombia',
      name: t('travel.colombia.name'),
      description: t('travel.colombia.description'),
      lat: 8.73,
      lng: -74.55,
      continent: t('continent.South America'),
      continentEmoji: '🦜',
      year: 2024,
    }),
    makePlace(['DJI_0805', 'DJI_0817', 'DJI_0849', 'DJI_0881'], {
      id: 'costa-rica',
      name: t('travel.costa-rica.name'),
      description: t('travel.costa-rica.description'),
      lat: 9.30,
      lng: -84.16,
      continent: t('continent.North America'),
      continentEmoji: '🐒',
      year: 2024,
    }),
    makePlace(['DJI_0768', 'DJI_0776'], {
      id: 'panama',
      name: t('travel.panama.name'),
      description: t('travel.panama.description'),
      lat: 9.63,
      lng: -82.67,
      continent: t('continent.North America'),
      continentEmoji: '🌊',
      year: 2024,
    }),
  ];
}
