export interface TravelPlace {
  id: string;
  name: string;
  description: string;
  lat: number;
  lng: number;
  photos: string[];
  thumbs: string[];
  blurs: (string | undefined)[];
  continent: string;
  continentEmoji: string;
}

const BASE = `${import.meta.env.BASE_URL}travel-map`;

/**
 * Set of photo IDs that have a corresponding *-blur.webp asset committed
 * in public/travel-map. Generated by checking the directory listing.
 */
const HAS_BLUR = new Set([
  'DJI_0006', 'DJI_0018', 'DJI_0022', 'DJI_0022 2', 'DJI_0027', 'DJI_0029',
  'DJI_0036', 'DJI_0049', 'DJI_0055', 'DJI_0070', 'DJI_0090', 'DJI_0092',
  'DJI_0111', 'DJI_0118', 'DJI_0125', 'DJI_0140', 'DJI_0149', 'DJI_0154',
  'DJI_0160', 'DJI_0169', 'DJI_0171', 'DJI_0179', 'DJI_0182', 'DJI_0194',
  'DJI_0203', 'DJI_0216', 'DJI_0258', 'DJI_0265', 'DJI_0271', 'DJI_0274',
  'DJI_0275', 'DJI_0327', 'DJI_0336', 'DJI_0346', 'DJI_0361', 'DJI_0495',
  'DJI_0500', 'DJI_0503', 'DJI_0521', 'DJI_0539', 'DJI_0559',
]);

function makePlace(
  ids: string[],
  meta: Omit<TravelPlace, 'photos' | 'thumbs' | 'blurs'>,
): TravelPlace {
  return {
    ...meta,
    photos: ids.map(f => `${BASE}/${f}.webp`),
    thumbs: ids.map(f => `${BASE}/${f}-thumb.webp`),
    blurs: ids.map(f => HAS_BLUR.has(f) ? `${BASE}/${f}-blur.webp` : undefined),
  };
}

export const travelPlaces: TravelPlace[] = [
  makePlace(['DJI_0006', 'DJI_0027', 'DJI_0036'], {
    id: 'iceland',
    name: 'Iceland',
    description: 'Land of fire and ice — volcanic landscapes, glaciers, waterfalls, and endless horizons from the drone.',
    lat: 64.75,
    lng: -17.84,
    continent: 'Europe',
    continentEmoji: '🧊',
  }),
  makePlace(['DJI_0018', 'DJI_0022', 'DJI_0070', 'DJI_0090', 'DJI_0092', 'DJI_0111', 'DJI_0125', 'DJI_0140'], {
    id: 'canadian-rockies',
    name: 'Canadian Rockies',
    description: 'Turquoise lakes, towering peaks, and pristine wilderness across British Columbia and Alberta.',
    lat: 52.24,
    lng: -118.62,
    continent: 'North America',
    continentEmoji: '🏔️',
  }),
  makePlace(['DJI_0022 2', 'DJI_0029'], {
    id: 'malaysia',
    name: 'Malaysia',
    description: 'Tropical beaches, Kuala Lumpur skyline, and lush jungles of Southeast Asia.',
    lat: 4.31,
    lng: 100.99,
    continent: 'Asia',
    continentEmoji: '🌴',
  }),
  makePlace(['DJI_0049', 'DJI_0055', 'DJI_0118', 'DJI_0149', 'DJI_0171'], {
    id: 'bali',
    name: 'Bali',
    description: 'Rice terraces, temple ceremonies, dramatic cliffs, and endless sunsets over the Indian Ocean.',
    lat: -8.47,
    lng: 115.27,
    continent: 'Asia',
    continentEmoji: '🌺',
  }),
  makePlace(['DJI_0154', 'DJI_0160'], {
    id: 'yosemite',
    name: 'Yosemite',
    description: 'Granite cliffs, giant sequoias, and the breathtaking valley views of California\'s crown jewel.',
    lat: 37.77,
    lng: -119.81,
    continent: 'North America',
    continentEmoji: '🏞️',
  }),
  makePlace(['DJI_0169', 'DJI_0179', 'DJI_0182'], {
    id: 'silicon-valley',
    name: 'Silicon Valley',
    description: 'The tech capital of the world — aerial views over San Jose and the Bay Area.',
    lat: 37.34,
    lng: -122.01,
    continent: 'North America',
    continentEmoji: '💻',
  }),
  makePlace(['DJI_0194', 'DJI_0203', 'DJI_0216', 'DJI_0258', 'DJI_0265', 'DJI_0271', 'DJI_0274', 'DJI_0275', 'DJI_0346', 'DJI_0361'], {
    id: 'mexican-caribbean',
    name: 'Mexican Caribbean',
    description: 'Turquoise waters, ancient Mayan ruins, cenotes, and white sand beaches along the Riviera Maya.',
    lat: 20.80,
    lng: -87.19,
    continent: 'North America',
    continentEmoji: '🏖️',
  }),
  makePlace(['DJI_0327', 'DJI_0336', 'DJI_0495', 'DJI_0500', 'DJI_0503', 'DJI_0521'], {
    id: 'yucatan',
    name: 'Yucatán',
    description: 'Pink flamingo lagoons, Mayan pyramids, and colorful colonial towns deep in the Mexican interior.',
    lat: 20.58,
    lng: -89.35,
    continent: 'North America',
    continentEmoji: '🏛️',
  }),
  makePlace(['DJI_0539', 'DJI_0559', 'DJI_0573'], {
    id: 'guatemala',
    name: 'Guatemala',
    description: 'Volcanoes, misty highlands, Lake Atitlán, and the ancient ruins of Tikal from above.',
    lat: 14.99,
    lng: -90.21,
    continent: 'North America',
    continentEmoji: '🌋',
  }),
  makePlace(['DJI_0596', 'DJI_0607', 'DJI_0610', 'DJI_0635'], {
    id: 'ecuador',
    name: 'Ecuador',
    description: 'The equator line, Andean highlands, cloud forests, and the diversity of a tiny, mighty country.',
    lat: -0.25,
    lng: -78.38,
    continent: 'South America',
    continentEmoji: '🌿',
  }),
  makePlace(['DJI_0659', 'DJI_0701', 'DJI_0712', 'DJI_0753', 'DJI_0766', 'DJI_0802', 'DJI_0815', 'DJI_0818', 'DJI_0859'], {
    id: 'colombia',
    name: 'Colombia',
    description: 'Caribbean coastline, colonial Cartagena, lush coffee country, and vibrant cities from the sky.',
    lat: 8.73,
    lng: -74.55,
    continent: 'South America',
    continentEmoji: '🦜',
  }),
  makePlace(['DJI_0805', 'DJI_0817', 'DJI_0849', 'DJI_0881'], {
    id: 'costa-rica',
    name: 'Costa Rica',
    description: 'Pura vida — rainforests, volcanoes, wild coastlines, and incredible biodiversity.',
    lat: 9.30,
    lng: -84.16,
    continent: 'North America',
    continentEmoji: '🐒',
  }),
  makePlace(['DJI_0768', 'DJI_0776'], {
    id: 'panama',
    name: 'Panama',
    description: 'Where two oceans meet — tropical islands, misty highlands, and the famous canal from above.',
    lat: 9.63,
    lng: -82.67,
    continent: 'North America',
    continentEmoji: '🌊',
  }),
];
